import type { Metadata, Viewport } from "next";
import localFont from "next/font/local";
import { Sidebar } from "@/components/sidebar";

import "./globals.css";

const alkTallMtavruli = localFont({
  src: "../public/alk-tall-mtavruli.otf",
  variable: "--font-alk-tall",
});

const cobaltDisplay = localFont({
  src: "../public/cobalt-display.woff2",
  variable: "--font-cobalt",
});

export const metadata: Metadata = {
  title: "გრაფიტი",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${alkTallMtavruli.variable} ${cobaltDisplay.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col font-alk-tall">
        <Sidebar />
        {children}
      </body>
    </html>
  );
}
